### PR TITLE
Add _join method + CI pipeline

### PR DESCRIPTION
**Pull request by timothyas**
We've run into simple path related bugs more than once due to the fact that we are running code on different operating systems (*nix vs windows) but sometimes the paths we create are actually for the cloud. This means that `os.path.join` does not always work. I've recently found that `Pathlib` also does not work for the cloud because it converts`//`->`/` from e.g. `s3://` or `https://`.

Example: 
Windows user wants to read from bucket `s3://mybucket/fv3.zarr`. `os.path.join` turns this into `s3:\\mybucket\fv3.zarr` (or something, I don't know windows) 

On linux if we were using Pathlib to read from that bucket, the path would become `s3:/mybucket/fv3.zarr`

So this PR makes `UFSDataset` recognize `s3://`, `gcs://` or `https://` paths and treats them properly, otherwise deferring to `os.path.join`.

Also, this adds a simple unit test to make sure the join operation is correct as well as a CI workflow to test this on linux, macos, and windows.

### CODE REVIEW

**Comment by timothyas** [comment]
@HTFWitt this PR should solve the cloud vs local OS path problems.

**Comment by HTFWitt** [comment]
@timothyas This does work in my quick tests.  I see you lean towards os.path.join, which works, and I use Pathlib (personal preference), but I also found there is a [cloudpathlib](https://cloudpathlib.drivendata.org/stable/) library that may be of some use.

**Comment by HTFWitt** [comment]
Note: Is the principal use of the Jupyter Notebooks to be a quick-start example code?  If so, it may be advantageous to document the library dependencies needed for it to run.  When I ran through the CICE notebook, I had several 'optional' libraries that needed to be installed to get it to run.  A couple of comments at the start would help newbies (like me.)

**Comment by timothyas** [comment]
Thanks @HTFWitt! Yes I have a slight preference for `os`, but it's only because I can remember the functions by memory and haven't used Pathlib (yet). Regarding `CloudPathlib`, that's a good call and could be useful. I'll suggest we keep that in mind for future reference if we need more complicated functionality, since right now we're just forming paths and we don't need to run commands like copy, move, etc. If we do though, I think it would be good to move to a Pathlib/CloudPathlib combo, assuming those two play nicely together. 

Also great comment regarding the docs. We should address that so it's easy to reproduce the documentation, which I'm assuming people will want to do.

**Comment by timothyas** [comment]
Note that this PR sets up a CI pipeline which in the future will run on pull requests. It should all work for linux, macos, and windows since it worked for the branch that this PR sits on (see [here](https://github.com/timothyas/ufs2arco/actions/runs/7107384098)).

**Comment by timothyas** [comment]
@frolovsa this is ready for your review whenever you get a chance

**Review by frolovsa — APPROVED** [review]
looks good, Tim. thank you and Ken for looking through the details

**Comment by timothyas** [comment]
Thanks everyone! Merging this now

**Pull request merged**
